services:
  web:
    build:
      context: .
      args:
        VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
        VITE_EMAILJS_TEMPLATE_ID: ${VITE_EMAILJS_TEMPLATE_ID}
        VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_PUBLIC_KEY}
    ports:
      - "8080:80"
    restart: unless-stopped
